dWeb.Auger.Drilling/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dWeb.Auger.Drilling.Controllers
{
    public class ManagementController : Controller
    {
        // GET: Management
        public ActionResult Index()
        {
            return View(new Models.ManagementViewModel()
            {
                regModel = new Models.RegisterViewModel()
                {
                    UserRoles = GetFakeRoles()
                }
            });
        }

        public static List<SelectListItem> GetFakeRoles()
        {
            List<SelectListItem> FakeRoles = new List<SelectListItem>();
            Dictionary<string, string> Roles = new Dictionary<string, string>()
            {
                { "1", "Administrator" }, {"2", "Office" }, {"3", "Operator" }, {"4", "Maintenance" }, {"5", "Standard" }
            };
            foreach (var role in Roles)
            {
                FakeRoles.Add(new SelectListItem()
                {
                    Selected = (role.Key == "5") ? true : false,                       
                    Text = role.Value,
                    Value = role.Key
                });
            }

            return FakeRoles;
        }
    }
}

dWeb.Auger.Drilling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Auger Drilling</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AD Maintenance", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Maintenance", "Index", "Maintenance")</li>
                    <li>@Html.ActionLink("Purchase Orders", "Index", "Management")</li>
                    <li>@Html.ActionLink("Management", "Index", "Management")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Down Time Tracking
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="width:200px!important;">
                            <li><a href="~/DTT/Index">Rig Tracking</a></li>
                            <li><a href="~/DTT/InService">Rig Servicing</a></li>
                        </ul>
                    </li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        
    </div>
    <hr />
    <div class="container">
        <footer>
            <p>&copy; @DateTime.Now.Year - Auger Drilling. All Rights Reserved.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

dWeb.Auger.Drilling/Views/Shared/_LayoutNon.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Auger Drilling</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AD Maintenance", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Auger Drilling. All Rights Reserved.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>